### ISSUE TITLE
mintstick refuse to start on LMDE6

### ISSUE THREAD

**Issue by thegreatyellow67** [linuxmint/mintstick#133]
Hi, I'm using LMDE6, today I'm trying to launch mintstick with command:

$ mintstick -m iso

and so I get and error:

Traceback (most recent call last):
  File "/usr/lib/mintstick/mintstick.py", line 573, in <module>
    MintStick(iso_path, usb_path, filesystem, mode, debug)
  File "/usr/lib/mintstick/mintstick.py", line 55, in __init__
    self.udisks_client = UDisks.Client.new_sync()
                         ^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)

What's wrong? How can I fix this issue?
Thanks!

**Comment by thegreatyellow67** [comment]
Simply restarting system the issue was fixed.
