### ISSUE TITLE
Error while trying to write (OpenSUSE)

### ISSUE THREAD

**Issue by silviucc** [linuxmint/mintstick#34]
I'm trying to get mintstick to work on OpenSUSE 13.2. I get this message when running from command line:

```
silviu@linux-hr4u:~> mintstick -m iso Downloads/ubuntu-14.04
ubuntu-14.04.1-desktop-amd64.iso  ubuntu-14.04-startup-sounds.zip   
silviu@linux-hr4u:~> mintstick -m iso Downloads/ubuntu-14.04.1-desktop-amd64.iso 
/usr/lib/mintstick/mintstick.py:64: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.wTree.add_from_file(self.gladefile)
/usr/lib/mintstick/mintstick.py:64: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.wTree.add_from_file(self.gladefile)
/usr/lib/mintstick/mintstick.py:64: Warning: The property GtkImage:stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.wTree.add_from_file(self.gladefile)
/usr/lib/mintstick/mintstick.py:64: Warning: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.wTree.add_from_file(self.gladefile)
raw_write took 4.110 ms
Traceback (most recent call last):
  File "/usr/lib/mintstick/raw_write.py", line 85, in <module>
    main()
  File "/usr/lib/mintstick/raw_write.py", line 82, in main
    raw_write(source, target)
  File "/usr/lib/mintstick/raw_write.py", line 41, in raw_write
    os.fsync(output.fileno())
OSError: [Errno 5] Input/output error
Image: /home/silviu/Downloads/ubuntu-14.04.1-desktop-amd64.iso
USB stick: /dev/sdf
Starting copy from /home/silviu/Downloads/ubuntu-14.04.1-desktop-amd64.iso to /dev/sdf
An error occurred.
```

This is what I see in dmesg:

```
[ 5716.379808]  sdf: sdf1 sdf2
[ 5716.463196] usb 1-1.6: reset high-speed USB device number 5 using ehci-pci
[ 5716.550486] sd 12:0:0:0: [sdf] Unhandled sense code
[ 5716.550489] sd 12:0:0:0: [sdf]  
[ 5716.550490] Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[ 5716.550491] sd 12:0:0:0: [sdf]  
[ 5716.550492] Sense Key : Vendor Specific(9) [current] 
[ 5716.550494] Info fld=0x0
[ 5716.550495] sd 12:0:0:0: [sdf]  
[ 5716.550496] Add. Sense: Logical unit not ready, cause not reportable
[ 5716.550497] sd 12:0:0:0: [sdf] CDB: 
[ 5716.550498] Write(10): 2a 00 00 00 4e 80 00 00 f0 00
[ 5716.550502] end_request: I/O error, dev sdf, sector 20096
[ 5716.550504] Buffer I/O error on device sdf, logical block 2512
[ 5716.550505] lost page write due to I/O error on sdf
[ 5716.550510] Buffer I/O error on device sdf, logical block 2513
[ 5716.550510] lost page write due to I/O error on sdf
[ 5716.550512] Buffer I/O error on device sdf, logical block 2514
[ 5716.550513] lost page write due to I/O error on sdf
[ 5716.550515] Buffer I/O error on device sdf, logical block 2515
[ 5716.550515] lost page write due to I/O error on sdf
[ 5716.550517] Buffer I/O error on device sdf, logical block 2516
[ 5716.550518] lost page write due to I/O error on sdf
[ 5716.550520] Buffer I/O error on device sdf, logical block 2517
[ 5716.550520] lost page write due to I/O error on sdf
[ 5716.550522] Buffer I/O error on device sdf, logical block 2518
[ 5716.550523] lost page write due to I/O error on sdf
[ 5716.550525] Buffer I/O error on device sdf, logical block 2519
[ 5716.550525] lost page write due to I/O error on sdf
[ 5716.550527] Buffer I/O error on device sdf, logical block 2520
[ 5716.550528] lost page write due to I/O error on sdf
[ 5716.550530] Buffer I/O error on device sdf, logical block 2521
[ 5716.550530] lost page write due to I/O error on sdf
```

**Comment by silviucc** [comment]
This appears to be fixed. I tested on Leap 42.1.

For some reason OpenSUSE do not include python-parted in their repos but can be found on software.opensuse.org
