### ISSUE TITLE
CLI formatting - NameError

### ISSUE THREAD

**Issue by fhdk** [linuxmint/mintstick#75]
---
When using command line to format a warning and an error occurs
Quite easy to reproduce - replace sdy - with the testing device

Manjaro
Python 3.8

---
```
❯ mintstick -m format -u /dev/sdy -f vfat
/usr/lib/mintstick/mintstick.py:40: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
Traceback (most recent call last):
  File "/usr/lib/mintstick/mintstick.py", line 602, in <module>
    MintStick(iso_path, usb_path, filesystem, mode, debug)
  File "/usr/lib/mintstick/mintstick.py", line 181, in __init__
    iter = model.get_iter_first()
NameError: name 'model' is not defined
```

**Comment by fhdk** [comment]
Fixed with https://github.com/linuxmint/mintstick/pull/76
